# Site settings
title: Venue Media
email: info@venuemediagroup.com
copyright: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 Venue Media Group
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://venuemediagroup.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Pretty URL
permalink: "posts/:title"

# Custom categories
categories: [navbar]

sass:
    style: :compressed
