# Site settings
title: Digital Signage
email: adamjblanchard1@gmail.com
copyright: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 Venue Media
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Pretty URL
permalink: "posts/:title"

# Custom categories
categories: [navbar]

sass:
    style: :compressed
